var menudata={children:[
{text:"Página principal",url:"index.html"},
{text:"Archivos",url:"files.html",children:[
{text:"Lista de archivos",url:"files.html"},
{text:"Globales",url:"globals.html",children:[
{text:"Todo",url:"globals.html",children:[
{text:"_",url:"globals.html#index__"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"i",url:"globals.html#index_i"},
{text:"k",url:"globals.html#index_k"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"v",url:"globals.html#index_v"}]},
{text:"Funciones",url:"globals_func.html",children:[
{text:"b",url:"globals_func.html#index_b"},
{text:"c",url:"globals_func.html#index_c"},
{text:"i",url:"globals_func.html#index_i"},
{text:"k",url:"globals_func.html#index_k"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"p",url:"globals_func.html#index_p"},
{text:"r",url:"globals_func.html#index_r"},
{text:"s",url:"globals_func.html#index_s"}]},
{text:"Variables",url:"globals_vars.html"},
{text:"Enumeraciones",url:"globals_enum.html"},
{text:"Valores de enumeraciones",url:"globals_eval.html"},
{text:"defines",url:"globals_defs.html",children:[
{text:"b",url:"globals_defs.html#index_b"},
{text:"d",url:"globals_defs.html#index_d"},
{text:"e",url:"globals_defs.html#index_e"},
{text:"i",url:"globals_defs.html#index_i"},
{text:"l",url:"globals_defs.html#index_l"},
{text:"m",url:"globals_defs.html#index_m"},
{text:"r",url:"globals_defs.html#index_r"}]}]}]}]}
